version: '3.9'

services:
  web-d:
    # image: php:7.0-apache
    build: './module_d_php'
    ports:
      - "8084:80"
    volumes:
      - ./module_d_php:/var/www/html
    depends_on:
      - db
  web-d-react:
    build: './module_d_react'
    ports:
      - "8085:80"
    volumes:
      - ./module_d_react:/var/www/html
  web:
    # image: php:7.0-apache
    build: './module_c'
    ports:
      - "8081:80"
    volumes:
      - ./module_c:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password